backend:
  name: git-gateway
  branch: main

site_url: https://un-nouvel-elan-saint-branchs.github.io/un-nouvel-elan-saint-branchs

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
